import type { DrugRecord } from "./types";

// 注意: これはスケルトン用のサンプルデータ。
// 本番では ETL（src/lib/etl/*）が一次情報を取り込み、この配列を置き換える。
// 実在の品名・コードを含むが、供給状況・日付は架空のデモ値であり実態を保証しない。
export const SEED_DRUGS: DrugRecord[] = [
  {
    id: "seed-001",
    yjCode: "3399009F1020",
    originalDrug: "プラスグレル塩酸塩錠",
    brandName: "エフィエント錠",
    ingredient: "プラスグレル塩酸塩",
    therapeuticClass: "その他の血液・体液用薬",
    representativeSpec: "2.5mg1錠",
    supplyStatus: "限定出荷",
    sourceType: "厚労省",
    sourceDetail: "厚労省 医療用医薬品供給状況報告（デモ: 2026/6/1現在 ほか11規格）",
    sourceUrl: "https://www.mhlw.go.jp/",
    verifiedAt: "2026-06-01",
    confidence: "確定",
    shortageReason: "その他の理由",
    recoveryOutlook: "解消見込みあり",
    warningTags: ["在庫確認要"],
    clinicalNotes: ["後発品は複数社が通常出荷"],
    alternatives: [
      { name: "プラスグレル錠（後発: 東和薬品/第一三共エスファ）", note: "後発は通常出荷", insuranceCovered: true },
    ],
    fieldIntel: [
      {
        label: "official_reference_needed",
        target: "エフィエント錠2.5mg",
        summary: "自社事情による限定出荷として共有された。",
        note: "X由来情報は公式確定ではなく、厚労省版への現場補足として扱う。",
        observedAt: "2026-06-02",
      },
    ],
  },
  {
    id: "seed-002",
    yjCode: "2123014F1094",
    originalDrug: "アロチノロール塩酸塩錠",
    ingredient: "アロチノロール塩酸塩",
    therapeuticClass: "不整脈用剤",
    representativeSpec: "5mg1錠",
    supplyStatus: "限定出荷",
    sourceType: "日薬連",
    sourceDetail: "日薬連 供給状況調査（デモ）",
    verifiedAt: "2026-05-28",
    confidence: "確定",
    shortageReason: "複数社の市場撤退",
    recoveryOutlook: "未定",
    warningTags: ["代替困難", "保険適用に注意"],
    clinicalNotes: ["本態性振戦適応での代替が難しい"],
    alternatives: [
      { name: "インデラル（プロプラノロール）", note: "本態性振戦は保険適用外のケースあり", insuranceCovered: false },
    ],
    fieldIntel: [
      {
        label: "field_report",
        target: "アロチノロール塩酸塩錠5mg",
        summary: "本態性振戦での代替困難が慢性化。",
        observedAt: "2026-06-02",
      },
    ],
  },
  {
    id: "seed-003",
    yjCode: "3179534D1020",
    originalDrug: "ビタメジン配合カプセルB25",
    brandName: "ビタメジン配合カプセルB25",
    therapeuticClass: "混合ビタミン剤",
    representativeSpec: "1カプセル",
    supplyStatus: "限定出荷",
    sourceType: "SNS",
    sourceDetail: "現場情報（要公式確認）",
    verifiedAt: "2026-05-20",
    confidence: "速報",
    shortageReason: "関連他剤の販売中止の影響",
    recoveryOutlook: "未定",
    warningTags: ["要確認", "供給不安定"],
    clinicalNotes: ["複合ビタミン剤全体が不安定との現場指摘"],
    alternatives: [
      { name: "パンビタン末 等の複合ビタミン", note: "要確認", insuranceCovered: true },
    ],
    fieldIntel: [
      {
        label: "screenshot_observed",
        target: "ビタメジン配合カプセルB25",
        summary: "複合ビタミン剤が安定しないとの声。在庫逼迫の報告あり。",
        note: "明確な限定出荷発表は未確認。",
        postedBy: "@example_user",
        observedAt: "2026-06-02",
      },
    ],
  },
  {
    id: "seed-004",
    yjCode: "6149005F1086",
    originalDrug: "セフトリアキソンナトリウム静注用",
    ingredient: "セフトリアキソンナトリウム",
    therapeuticClass: "主としてグラム陽性・陰性菌に作用するもの",
    representativeSpec: "1g1瓶",
    supplyStatus: "供給停止",
    sourceType: "メーカー",
    sourceDetail: "製造販売元 出荷停止告知（デモ）",
    sourceUrl: "https://www.example-pharma.co.jp/",
    verifiedAt: "2026-05-30",
    confidence: "確定",
    shortageReason: "原薬調達難",
    recoveryOutlook: "2026年内見込み",
    warningTags: ["注射剤", "院内在庫要確認"],
    clinicalNotes: ["他社品で代替可能か確認"],
    alternatives: [
      { name: "セフォタキシム等の第3世代セフェム", note: "スペクトラム差に注意", insuranceCovered: true },
    ],
    fieldIntel: [],
  },
  {
    id: "seed-005",
    yjCode: "2590007F1323",
    originalDrug: "酸化マグネシウム錠",
    ingredient: "酸化マグネシウム",
    therapeuticClass: "制酸剤/緩下剤",
    representativeSpec: "330mg1錠",
    supplyStatus: "通常出荷",
    sourceType: "日薬連",
    sourceDetail: "日薬連 供給状況調査（デモ）",
    verifiedAt: "2026-06-01",
    confidence: "確定",
    warningTags: [],
    clinicalNotes: ["複数社が通常出荷"],
    alternatives: [],
    fieldIntel: [],
  },
  {
    id: "seed-006",
    yjCode: "1149019F1045",
    originalDrug: "アセトアミノフェン錠",
    ingredient: "アセトアミノフェン",
    therapeuticClass: "解熱鎮痛消炎剤",
    representativeSpec: "500mg1錠",
    supplyStatus: "限定出荷",
    sourceType: "厚労省",
    sourceDetail: "厚労省 医療用医薬品供給状況報告（デモ）",
    sourceUrl: "https://www.mhlw.go.jp/",
    verifiedAt: "2026-05-25",
    confidence: "確定",
    shortageReason: "需要増",
    recoveryOutlook: "改善傾向",
    warningTags: ["規格により変動"],
    clinicalNotes: ["200mg規格は通常出荷の社あり"],
    alternatives: [
      { name: "アセトアミノフェン200mg錠", note: "規格変更で対応可", insuranceCovered: true },
    ],
    fieldIntel: [],
  },
  {
    id: "seed-007",
    yjCode: "2649704M1120",
    originalDrug: "ヘパリン類似物質油性クリーム",
    therapeuticClass: "鎮痛・鎮痒・収れん・消炎剤",
    representativeSpec: "0.3% 1g",
    supplyStatus: "通常出荷",
    sourceType: "日薬連",
    sourceDetail: "日薬連 供給状況調査（デモ）",
    verifiedAt: "2026-06-01",
    confidence: "確定",
    warningTags: [],
    clinicalNotes: [],
    alternatives: [],
    fieldIntel: [],
  },
  {
    id: "seed-008",
    yjCode: "2171022F1037",
    originalDrug: "アムロジピンベシル酸塩錠",
    ingredient: "アムロジピンベシル酸塩",
    therapeuticClass: "血管拡張剤",
    representativeSpec: "5mg1錠",
    supplyStatus: "販売中止",
    sourceType: "メーカー",
    sourceDetail: "製造販売元 販売中止告知（デモ・特定銘柄）",
    verifiedAt: "2026-04-15",
    confidence: "確定",
    shortageReason: "製造終了",
    recoveryOutlook: "なし（他社品へ）",
    warningTags: ["銘柄指定処方に注意"],
    clinicalNotes: ["成分としては多数社が通常出荷"],
    alternatives: [
      { name: "アムロジピン錠（他社後発）", note: "成分同一", insuranceCovered: true },
    ],
    fieldIntel: [],
  },
];
